services:
  qwen2-math-72b:
    image: nvidia/cuda:12.8.0-devel-ubuntu24.04-py12-venv-v1.7
    container_name: Qwen2.5-Math-72B
    restart: unless-stopped

    ports:
      - "8015:8015"

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - /data/lx_code/llm_models:/home/workspace

    shm_size: "16g"
    ipc: host

    gpus:
      - count: 8
        capabilities: [gpu]

    working_dir: /home/workspace/Qwen2.5-Math-72B-Instruct

    command:
      - bash
      - -c
      - "source /mnt/py12_confucius3_math/bin/activate && lmdeploy serve api_server Qwen2.5-Math-72B-Instruct --server-port 8015 --dtype float16 --tp 8 --session-len 10240"
